name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm clean-install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
```
# Ensure GitHub Pages Is Configured Correctly
# 1. Navigate to your repository on GitHub: [https://github.com/Reeshon/Commerce](https://github.com/Reeshon/Commerce).
# 2. Click on **Settings**.
# 3. In the sidebar, select **Pages**.
# 4. Under **Source**, choose the `gh-pages` branch.
# 5. Click **Save**.