name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Remove node_modules and package-lock.json
      - name: Clean npm cache and remove node_modules
        run: |
          rm -rf node_modules package-lock.json

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the project
      - name: Build Project
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
# Ensure GitHub Pages Is Configured Correctly
# 1. Navigate to your repository on GitHub: [https://github.com/Reeshon/Commerce](https://github.com/Reeshon/Commerce).
# 2. Click on **Settings**.
# 3. In the sidebar, select **Pages**.
# 4. Under **Source**, choose the `gh-pages` branch.
# 5. Click **Save**.